const ROOMS = 'HOUSE-KEEPING/ROOMS_PAGE/';
export const ROOMS_REQUEST = `${ROOMS}ROOMS_REQUEST`;
export const ROOMS_SUCCESS = `${ROOMS}ROOMS_SUCCESS`;
export const ROOMS_FAILURE = `${ROOMS}ROOMS_FAILURE`;

export const TASKS_REQUEST = `${ROOMS}TASKS_REQUEST`;
export const TASKS_SUCCESS = `${ROOMS}TASKS_SUCCESS`;

export const AMENITIES_REQUEST = `${ROOMS}AMENITIES_REQUEST`;
export const AMENITIES_SUCCESS = `${ROOMS}AMENITIES_SUCCESS`;

export const STATUSES_REQUEST = `${ROOMS}STATUSES_REQUEST`;
export const STATUSES_SUCCESS = `${ROOMS}STATUSES_SUCCESS`;
