const AUTH = 'HOUSE-KEEPING/AUTH/';
export const AUTH_REQUEST = `${AUTH}AUTH-REQUEST`;
export const AUTH_SUCCESS = `${AUTH}AUTH-SUCCESS`;
export const AUTH_FAILURE = `${AUTH}AUTH-FAILURE`;
export const AUTH_LOGOUT = `${AUTH}AUTH_LOGOUT`;
