const ROOM = 'HOUSE-KEEPING/ROOM/';
export const ROOM_REQUEST = `${ROOM}ROOM_REQUEST`;
export const ROOM_SUCCESS = `${ROOM}ROOM_SUCCESS`;
export const ROOM_FAILURE = `${ROOM}ROOM_FAILURE`;
export const ROOM_SET = `${ROOM}ROOM_SET`; // обновление в сторе
export const ROOM_UPDATE_REQUEST = `${ROOM}ROOM_UPDATE_REQUEST`; // отправка на сервер
export const ROOM_UPDATE_SUCCESS = `${ROOM}ROOM_UPDATE_SUCCESS`;

export const ROOM_AMENITIES_LIST_REQUEST = `${ROOM}AMENITIES_LIST_REQUEST`;
export const ROOM_AMENITIES_LIST_SUCCESS = `${ROOM}AMENITIES_LIST_SUCCESS`;
export const ROOM_AMENITIES_SET_DEFAULT = `${ROOM}AMENITIES_SET_DEFAULT`;
export const ROOM_INCREASE_AMENITY = `${ROOM}INCREASE_AMENITY`;
export const ROOM_DECREASE_AMENITY = `${ROOM}DECREASE_AMENITY`;

export const ROOM_UPDATE_TODO_LIST = `${ROOM}UPDATE_TODO_LIST`;
